In [2]:
try:
    x = [1,2,3]
    for i in range(4):
        print(x[i])
except:
    print('except')

1
2
3
except


In [41]:
import torch
import torch.nn as nn
input = torch.randn(16, 3, 32, 32)
# downsample = nn.Conv2d(3, 16, kernel_size=3, stride=2, padding=1)(input)
# print(downsample.shape)
output = nn.ConvTranspose2d(3, 3, kernel_size=3)(input)
output = nn.ConvTranspose2d(3, 3, kernel_size=3, stride=2)(output)
output = nn.ConvTranspose2d(3, 3, kernel_size=5, stride=4)(output)
print(output.shape)
# print(output.shape)

# input = torch.Tensor([[1.0, 2.0],
#                       [3.0, 4.0]])
# input = input.reshape((1,1,2,2))
# print(input.shape)
# result = nn.ConvTranspose2d(1,1, kernel_size=3, stride=1, padding=0)(input)
# print(result.shape)
# print(result)

# result = nn.ConvTranspose2d(1,1, kernel_size=3, stride=2, padding=0, dilation=1)(input)
# print(result.shape)
# print(result)

torch.Size([16, 3, 277, 277])


In [50]:
import torch.nn as nn
from torchvision import models
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
print(model.fc.weight[0,0])
model.fc = nn.Sequential(
    model.fc,
    nn.Linear(2048,100)
)
# print(model)
print(model.fc[0].weight[0,0])

tensor(0.0112, grad_fn=<SelectBackward0>)
tensor(0.0112, grad_fn=<SelectBackward0>)


In [4]:
import time

start = time.time()
print(start)
time.sleep(2)
lap = time.time()-start
start = time.time()
time.sleep(2)
lap += time.time()-start
print(lap)

print(time.strftime('%H:%M:%S', time.localtime(lap)))

1660716148.2533243
4.006220102310181
00:00:04


In [61]:
def accuracy(output, target, topk=(1,)):
    """Computes the precision@k for the specified values of k"""
    maxk = max(topk)
    batch_size = target.size(0)

    _, pred = output.topk(maxk, 1, True, True)
    pred = pred.t() # transpose
    correct = pred.eq(target.reshape(1, -1).expand_as(pred))

    res = []
    for k in topk:
        correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
        wrong_k = batch_size - correct_k
        res.append(wrong_k.mul_(100.0 / batch_size))

    return res

import torch

output = torch.randn((128,10))
target = torch.randn((128))
# print(output.shape)
_,pred = (output.topk(5, 1, True, True))
print(pred[0])
print(pred.shape)
pred = pred.T
# print(pred.T.shape)
# print(output.size(0))
target[0] = output[0,pred[0,0]]
print(target.shape)
print(target.reshape(1,-1).shape)
print(target.reshape(1,-1).expand_as(pred).shape)
print(target.size(0))

correct = pred.eq(target.reshape(1, -1).expand_as(pred))
print(correct.shape)
print(correct[:5,0])
print(correct.reshape(-1).shape)
correct_k = correct[:5].reshape(-1).float().sum(0, keepdim=True)
print(correct_k)
print(correct_k.shape)

print()
wrong_k = target.size(0) - correct_k
print(wrong_k)
print(wrong_k.mul(100./target.size(0)))


tensor([9, 7, 6, 2, 1])
torch.Size([128, 5])
torch.Size([128])
torch.Size([1, 128])
torch.Size([5, 128])
128
torch.Size([5, 128])
tensor([False, False, False, False, False])
torch.Size([640])
tensor([0.])
torch.Size([1])

tensor([128.])
tensor([100.])


In [49]:
st = 'asdf'
temp = 'fjel,asdl'
print('hello {}, {temp1}'.format(st, temp1=temp))

err1 = 12
best_err1 = 1
is_best = err1 <= best_err1
print(is_best)

hello asdf, fjel,asdl
False


In [10]:
import torch.nn as nn
import torch
x = torch.Tensor([[1,2,3],
[1,2,3],
[3,2,1]])
print(x.shape)

print(nn.AvgPool1d(kernel_size=2,stride=1)(x))


torch.Size([3, 3])
tensor([[1.5000, 2.5000],
        [1.5000, 2.5000],
        [2.5000, 1.5000]])


In [3]:
import torch.nn as nn

class Bottleneck(nn.Module):
    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(Bottleneck, self).__init__()

        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * Bottleneck.expansion, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * Bottleneck.expansion)
        self.relu = nn.ReLU(inplace=True)

        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)
        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out

downsample = nn.Sequential(
                nn.Conv2d(16, 64, kernel_size=1, stride=1, bias=False),
                nn.BatchNorm2d(64),
            )

block = Bottleneck(16, 16, 1, downsample)
print(block)


Bottleneck(
  (conv1): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (downsample): Sequential(
    (0): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
)


In [2]:
from datetime import datetime
time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
print(type(time))

<class 'str'>


In [6]:
def func():
    global arge
    arge = 12

func()
print(arge)

12


In [3]:
act = False
print(3 if act else 123)

123


In [9]:
d = {'parameter':12, 'name':'jae'}
print(d)
print(type(d))
config = dict(nblock=[3,4,6,3], block='hello')
print(config)
def func(nblock, block):
    print(nblock)
    print(block)
print()
func(*config)
print()
func(**config)


{'parameter': 12, 'name': 'jae'}
<class 'dict'>
{'nblock': [3, 4, 6, 3], 'block': 'hello'}

nblock
block

[3, 4, 6, 3]
hello


In [12]:
class tmp():
    def __init__(self, width, base_width):
        self.width = width = 0
        print(self.width)

t = tmp(3, 2.3)

0


In [11]:
import torch
import torch.nn as nn

def conv3x3(in_planes, out_planes, stride=1):
    "3x3 convolution with padding"
    return nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=1, bias=False)



class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(BasicBlock, self).__init__()
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = nn.BatchNorm2d(planes)
        self.relu = nn.ReLU(inplace=True)

        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out



class Bottleneck(nn.Module):
    expansion = 4

    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(Bottleneck, self).__init__()

        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * Bottleneck.expansion, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * Bottleneck.expansion)
        self.relu = nn.ReLU(inplace=True)

        self.downsample = downsample
        self.stride = stride

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)
        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out



class SEblock(nn.Module):
    r = 16
    def __init__(self, channel):
        super(SEblock, self).__init__()

        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channel, channel//self.r, bias=False),
            nn.ReLU(),
            nn.Linear(channel//self.r, channel, bias=False),
            nn.Sigmoid(),
        )
    
    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.avg_pool(x)
        y = y.view(b, c)  # flatten
        y = self.fc(y)
        y = y.view(b, c, 1, 1)
        return x * y.expand_as(x) # y의 형상을 x로 맞추어줌



class CBAM(nn.Module):
    r = 16
    def __init__(self, channel):
        super(CBAM, self).__init__()

        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channel, channel//self.r, bias=False),
            nn.ReLU(),
            nn.Linear(channel//self.r, channel, bias=False),
        )

        self.conv7 = nn.Conv2d(2, 1, kernel_size=7, padding=7//2, bias=False)

    def forward(self, x):
        ## channel attention 과정 ##
        b, c, _, _ = x.size()
        y1 = self.avg_pool(x)
        y1 = y1.view(b, c)  # flatten
        y1 = self.fc(y1)
        y1 = y1.view(b, c, 1, 1)
        y2 = self.max_pool(x)
        y2 = y2.view(b, c)  # flatten
        y2 = self.fc(y2)
        y2 = y2.view(b, c, 1, 1)
        channel_attention = nn.Sigmoid()(y1 + y2)
        x = x * channel_attention.expand_as(x) # hadamard product (y의 형상을 x로 맞추어줌)

        ## spatial attention 과정 ##
        spatial_avg = torch.mean(x, dim=1) # channel이 0으로 되어 있어서 1로 바꿈
        b, size, _, = spatial_avg.size()
        spatial_avg = spatial_avg.view(b, 1, size, -1)
        spatial_max, _ = torch.max(x, dim=1) # channel이 0으로 되어 있어서 1로 바꿈
        b, size, _, = spatial_max.size()
        spatial_max = spatial_max.view(b, 1, size, -1)
        spatial_attention = torch.cat([spatial_avg, spatial_max], 1)
        spatial_attention = self.conv7(spatial_attention)
        spatial_attention = nn.Sigmoid()(spatial_attention)
        x = x * spatial_attention.expand_as(x)
        return x

import torch.nn as nn
import math

class ResNet(nn.Module):
    def __init__(self, dataset, depth, num_classes, bottleneck=False):
        super(ResNet, self).__init__()        
        self.dataset = dataset
        if self.dataset.startswith('cifar'): # if dataset is cifar...
            self.inplanes = 16
            # print(bottleneck)
            if bottleneck == True:
                n = int((depth - 2) / 9)
                block = Bottleneck
            else:
                n = int((depth - 2) / 6)
                block = BasicBlock

            self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=3, stride=1, padding=1, bias=False)
            self.bn1 = nn.BatchNorm2d(self.inplanes)
            self.relu = nn.ReLU(inplace=True)
            self.layer1 = self._make_layer(block, 16, n)
            self.layer2 = self._make_layer(block, 32, n, stride=2)
            self.layer3 = self._make_layer(block, 64, n, stride=2) 
            self.avgpool = nn.AvgPool2d(8)
            self.fc = nn.Linear(64 * block.expansion, num_classes)

        elif dataset == 'imagenet': # if dataset is imagenet
            blocks ={18: BasicBlock, 34: BasicBlock, 50: Bottleneck, 101: Bottleneck, 152: Bottleneck, 200: Bottleneck}
            layers ={18: [2, 2, 2, 2], 34: [3, 4, 6, 3], 50: [3, 4, 6, 3], 101: [3, 4, 23, 3], 152: [3, 8, 36, 3], 200: [3, 24, 36, 3]}
            assert layers[depth], 'invalid detph for ResNet (depth should be one of 18, 34, 50, 101, 152, and 200)'

            self.inplanes = 64
            self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3, bias=False)
            self.bn1 = nn.BatchNorm2d(64)
            self.relu = nn.ReLU(inplace=True)
            self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
            self.layer1 = self._make_layer(blocks[depth], 64, layers[depth][0])
            self.layer2 = self._make_layer(blocks[depth], 128, layers[depth][1], stride=2)
            self.layer3 = self._make_layer(blocks[depth], 256, layers[depth][2], stride=2)
            self.layer4 = self._make_layer(blocks[depth], 512, layers[depth][3], stride=2)
            self.avgpool = nn.AvgPool2d(7) 
            self.fc = nn.Linear(512 * blocks[depth].expansion, num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        if self.dataset == 'cifar10' or self.dataset == 'cifar100':
            x = self.conv1(x)
            x = self.bn1(x)
            x = self.relu(x)
            
            x = self.layer1(x)
            x = self.layer2(x)
            x = self.layer3(x)

            x = self.avgpool(x)
            x = x.view(x.size(0), -1)
            x = self.fc(x)

        elif self.dataset == 'imagenet':
            x = self.conv1(x)
            x = self.bn1(x)
            x = self.relu(x)
            x = self.maxpool(x)

            x = self.layer1(x)
            x = self.layer2(x)
            x = self.layer3(x)
            x = self.layer4(x)

            x = self.avgpool(x)
            x = x.view(x.size(0), -1)
            x = self.fc(x)
    
        return x

model = ResNet('cifar-10', 10, )